[project]
org-name= "thisaru"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/kafka-avro-serializer-5.4.1.jar"
    artifactId = "kafka-avro-serializer"
    version = "5.4.1"
    groupId = "io.confluent"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/kafka-schema-registry-client-5.4.1.jar"
    artifactId = "kafka-schema-registry-client"
    version = "5.4.1"
    groupId = "io.confluent"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/common-config-5.4.1.jar"
    artifactId = "common-config"
    version = "5.4.1"
    groupId = "io.confluent"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/avro-1.9.2.jar"
    artifactId = "avro"
    version = "1.9.2"
    groupId = "org.apache.avro"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/common-utils-5.4.1.jar"
    artifactId = "common-utils"
    version = "5.4.1"
    groupId = "io.confluent"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/jackson-core-2.10.3.jar"
    artifactId = "jackson-core"
    version = "1.9.2"
    groupId = "com.fasterxml.jackson.core"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/jackson-databind-2.10.3.jar"
    artifactId = "jackson-databind"
    version = "2.10.3"
    groupId = "com.fasterxml.jackson.core"

    [[platform.libraries]]
    module = "producer"
    path = "./javalibs/jackson-annotations-2.10.3.jar"
    artifactId = "jackson-annotations"
    version = "2.10.3"
    groupId = "com.fasterxml.jackson.core"
